<?php
namespace frontend\models;
//use yii\db\ActiveRecord;
use Yii;
use yii\base\Model;
use yii\db\ActiveRecord;
use yii\helpers\Url;
class TR extends ActiveRecord
{
    public function activeRead()
    {
		Url::to(['site/index']);
//        return parent::activeAttributes(); // TODO: Change the autogenerated stub
    }
}